# Generated by Django 2.0.3 on 2018-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='node1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('val', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='node2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('val', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
